#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#               SparkyTools by FlailoftheLord.                     #
#         -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                  #
#           If you have any Questions or feedback                  #
#              Join my discord server here:                        #
#               https://discord.gg/wuxW5PS                         #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# Yeah... i don't think i'll be needing a config file... i'll add somethin' here if i do end up needing it.